version: '3.8'

services:
  flask_app:
    build: ./flask
    container_name: flask_container
    restart: always
    expose:
      - "5000"

  nginx:
    build: ./nginx
    container_name: nginx_container
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask_app
