apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-raydpcluster
spec:
  shutdownAfterJobFinishes: false
  entrypoint: python examples/pytorch_nyctaxi.py
  runtimeEnvYAML: |
    pip:
      - torch
      - torchvision
      - raydp
      - torchmetrics
    working_dir: "https://github.com/oap-project/raydp/archive/refs/heads/master.zip"
    env_vars:
      NUM_WORKERS: "2"
      CPUS_PER_WORKER: "2"

  rayClusterSpec:
    rayVersion: '2.9.0'
    headGroupSpec:
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-head
              image: onggizam/raydp:1.0.0
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                limits:
                  cpu: '1'
                  memory: '10G'
                requests:
                  cpu: '1'
                  memory: '10G'
    workerGroupSpecs:
      - replicas: 2
        minReplicas: 1
        maxReplicas: 5
        groupName: small-group
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: ray-worker
                image: onggizam/raydp:1.0.0
                resources:
                  limits:
                    cpu: '1'
                    memory: '10G'
                  requests:
                    cpu: '1'
                    memory: '10G'
