services:
  jupyter:
    build: .
    container_name: jupyter-container
    ports:
      - "1321:8888"
    volumes:
      - ./notebooks:/home/jupyter/work
    environment:
      - JUPYTER_TOKEN=
    restart: unless-stopped